import React, { useState } from "react";
import Head from "next/head";
import type { GetServerSideProps } from "next";

import {
  ExtraLargeText,
  OutlineButton,
  PrimaryButton,
  ProductCard,
  SemiboldText,
} from "../../components";
import { urlFor } from "../../lib/client";
import { fetchProducts } from "../../utils/fetchProducts";
import { fetchCategories } from "../../utils/fetchCategories";

interface Props {
  products: Product[];
  categories: Category[];
}

const Products = ({ products, categories }: Props) => {
  const dummyCategories = [
    "All Furniture",
    "Chairs",
    "Tables",
    "Sofas",
    "Cupboard",
  ];
  const dummyProducts = [
    {
      imageUrl: "/images/product1.png",
      title: "Smastad Cupboard",
      price: "Rp 1.229.500",
    },
    {
      imageUrl: "/images/product2.png",
      title: "Millberget Chair",
      price: "Rp 1.599.000",
    },
    {
      imageUrl: "/images/product3.png",
      title: "Landskrona Sofa",
      price: "Rp 3.495.000",
    },
    {
      imageUrl: "/images/product4.png",
      title: "Raskog troly",
      price: "Rp 229.000",
    },
    {
      imageUrl: "/images/product5.png",
      title: "Hemlingby Sofa",
      price: "Rp 1.229.500",
    },
    {
      imageUrl: "/images/product6.png",
      title: "Tommyard Table",
      price: "Rp 2.559.150",
    },
    {
      imageUrl: "/images/product7.png",
      title: "Sakarias Sofa",
      price: "Rp 1.895.000",
    },
    {
      imageUrl: "/images/product8.png",
      title: "Raskog Chair",
      price: "Rp 395.000",
    },
  ];
  const [categoriesActive, setCategoriesActive] = useState("All Furniture");

  return (
    <div className="bg-[#FAFAFA]">
      <Head>
        <title>FuniEra | Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-20 mt-[70px] mb-[120px] max-w-[1480px] 2xl:mx-auto">
        {/* Heading */}
        <section className="flex flex-col items-center">
          <SemiboldText
            textColor="text-[#D38669]"
            additonStyles="leading-[27px]"
          >
            Discover Our Best Furnitures
          </SemiboldText>
          <ExtraLargeText leading="leading-[68px]">
            Furniture Overview
          </ExtraLargeText>
          <div className="mt-[30px] grid w-full grid-cols-12 items-center justify-between">
            {/* Sort */}
            <div className="col-span-2">
              <OutlineButton
                label="Sort"
                borderColor="border-[#AAAAAA]"
                textColor="text-[#171627]"
              />
            </div>

            {/* Categories */}
            <div className="col-span-8 justify-self-center">
              {dummyCategories.map((category) => (
                <PrimaryButton
                  key={category}
                  label={category}
                  width="fit"
                  paddingX="px-[24px]"
                  paddingY="py-[14px]"
                  textColor={
                    categoriesActive !== category
                      ? "text-[#171627]]"
                      : "text-white"
                  }
                  background={
                    categoriesActive !== category
                      ? "bg-transparent"
                      : "bg-[#D38669]"
                  }
                />
              ))}
            </div>

            {/* Filter */}
            <div className="col-span-2 justify-self-end">
              <OutlineButton
                label="Filter"
                borderColor="border-[#AAAAAA]"
                textColor="text-[#171627]"
              />
            </div>
          </div>
        </section>

        {/* Products */}
        <section className="mt-[60px] grid grid-cols-4 gap-x-[30px] gap-y-[50px]">
          {products.map((product) => (
            <ProductCard
              key={product._id}
              slug={product.slug}
              imageUrl={product.images[0].url}
              title={product.name}
              price={product.price}
            />
          ))}
        </section>
      </main>
    </div>
  );
};

export default Products;

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const products = await fetchProducts();
  const categories = await fetchCategories();

  return {
    props: {
      products,
      categories,
    },
  };
};
