import type { GetServerSideProps } from "next";
import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import {
  ExtraLargeText,
  OutlineButton,
  PrimaryButton,
  ProductCard,
  SemiboldText,
} from "../../components";
import {
  fetchProducts,
  fetchProductsByCategory,
} from "../../utils/fetchProducts";
import { fetchCategories } from "../../utils/fetchCategories";

interface Props {
  products: Product[];
  categories: Category[];
}

const Products = ({ products, categories }: Props) => {
  const router = useRouter();
  const categoryQuery = router.query.category;

  return (
    <div className="bg-[#FAFAFA]">
      <Head>
        <title>FuniEra | Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-20 mt-[70px] mb-[120px] max-w-[1480px] 2xl:mx-auto">
        {/* Heading */}
        <section className="flex flex-col items-center">
          <SemiboldText
            textColor="text-[#D38669]"
            additonStyles="leading-[27px]"
          >
            Discover Our Best Furnitures
          </SemiboldText>
          <ExtraLargeText leading="leading-[68px]">
            Furniture Overview
          </ExtraLargeText>
          <div className="mt-[30px] grid w-full grid-cols-12 items-center justify-between">
            {/* Sort */}
            <div className="col-span-2">
              <OutlineButton
                label="Sort"
                borderColor="border-[#AAAAAA]"
                textColor="text-[#171627]"
              />
            </div>

            {/* Categories */}
            <div className="col-span-8 justify-self-center">
              <PrimaryButton
                label={"All Furniture"}
                width="fit"
                paddingX="px-[24px]"
                paddingY="py-[14px]"
                textColor={categoryQuery ? "text-[#171627]]" : "text-white"}
                background={categoryQuery ? "bg-transparent" : "bg-[#D38669]"}
                onClick={() => {
                  router.push("/products");
                }}
              />
              {categories.map((category) => (
                <PrimaryButton
                  key={category._id}
                  label={category.title}
                  width="fit"
                  paddingX="px-[24px]"
                  paddingY="py-[14px]"
                  textColor={
                    categoryQuery !== category.slug.current
                      ? "text-[#171627]]"
                      : "text-white"
                  }
                  background={
                    categoryQuery !== category.slug.current
                      ? "bg-transparent"
                      : "bg-[#D38669]"
                  }
                  onClick={() => {
                    router.push(`/products?category=${category.slug.current}`);
                  }}
                />
              ))}
            </div>

            {/* Filter */}
            <div className="col-span-2 justify-self-end">
              <OutlineButton
                label="Filter"
                borderColor="border-[#AAAAAA]"
                textColor="text-[#171627]"
              />
            </div>
          </div>
        </section>

        {/* Products */}
        <section className="mt-[60px] grid grid-cols-4 gap-x-[30px] gap-y-[50px]">
          {products.map((product) => (
            <ProductCard
              key={product._id}
              slug={product.slug}
              imageUrl={product.images[0].url}
              title={product.name}
              price={product.price}
            />
          ))}
        </section>
      </main>
    </div>
  );
};

export default Products;

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  let products: Product[];
  const { category } = context.query;

  if (category) {
    products = await fetchProductsByCategory(`${category}`);
  } else {
    products = await fetchProducts();
  }

  const categories = await fetchCategories();

  return {
    props: {
      products,
      categories,
    },
  };
};
